### PR TITLE
Update LAB_AK_01_Implementing_identity_services_and_Group_Policy.md

### PR DESCRIPTION
**Pull request by jkulbe-msft**
fixed PowerShell command line syntax error caused by backslashes in front of $true/$false"

# Module: 00
## Lab/Demo: 00

Fixes # . Removed extra backslahes causing a syntax error in PowerShell

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by autosysops** [comment]
agreed, but why not remove the : also?

**Comment by jkulbe-msft** [comment]
The ":" are needed to switch parameters, see https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.2#switch-parameter-design-considerations

**Comment by v-asamim** [comment]
Hello @jkulbe-msft, your request has been added to this PR #51.

**Comment by TJGitHubUser** [comment]
updated in PR #51

**Pull request closed without merging**
